# Generated by Django 3.1 on 2020-08-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=20, max_digits=25)),
                ('y', models.DecimalField(decimal_places=20, max_digits=25)),
                ('name', models.CharField(max_length=18)),
            ],
        ),
    ]
