# Generated by Django 3.1 on 2020-08-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map1app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='res_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
