# Generated by Django 3.1 on 2020-08-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map1app', '0002_maps_res_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maps',
            name='name',
        ),
        migrations.RemoveField(
            model_name='maps',
            name='x',
        ),
        migrations.RemoveField(
            model_name='maps',
            name='y',
        ),
        migrations.AddField(
            model_name='maps',
            name='locate_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='maps',
            name='locate_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='maps',
            name='res_name',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
